import { WEAPONS } from './config.js';

export const G = {
    state: 'lobby',
    player: {
        health: 100, maxHealth: 100,
        pos: new THREE.Vector3(0, 1.7, 0),
        grenades: 3,
        baseSpeed: 6.5, sprint: 10.5,
        y: 1.7, radius: 0.4,
    },
    mult: { damage:1, fireRate:1, reload:1, speed:1, pellets:0, pierce:0, head:2.5, mag:0, lifesteal:0 },
    attach: { mag:0, sup:0, scope:0 },
    weapons: WEAPONS.map(w => ({ ...w, ammo: w.mag })),
    curWeapon: 0,
    weaponReloading: false, weaponReloadTimer: 0, weaponTimer: 0, meleeCd: 0,
    firing: false, aiming: false,
    hitStop: 0,
    keys: {},
    recoil: { p:0, y:0 }, shake: 0,
    yaw: 0, pitch: 0,
    game: {
        score: 0, kills: 0, wave: 0,
        xp: 0, level: 1, xpToNext: 50,
        waveActive: false, toSpawn: 0, spawnTimer: 0, intermission: 3,
        combo: 0, comboTimer: 0, cash: 0,
        perks: [], bought: [],
        timer: 0, beaconHp: 1000, beaconMaxHp: 1000,
        shots: 0, hits: 0, headshots: 0,
    },
    mode: 'endless',
    profile: '',
    god: false,
    boss: null,
    pendingLevelUps: 0,
    settings: { sensitivity: 1, volume: 0.6, gfx: 'medium' },
    ownedWeapons: { 0:true, 1:false, 2:false, 3:false },
    career: { credits: 0, upg: { health:0, cash:0, grenades:0, rifle:0 } },
    best: { score: 0, wave: 0 },
    leaderboard: [],
};
